spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        type: debug
        default_batch_fetch_size: 100
    open-in-view: false
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/logapro
      username: seongwou
      password: seongwou1!

logging.level.org.springframework.batch: DEBUG
logging.level.org.springframework.transaction: DEBUG
logging.level.org.springframework.orm.jpa: DEBUG
logging.level.org.hibernate.SQL: DEBUG
logging.level.ch.qos.logback: DEBUG
logging.level.org.slf4j: DEBUG